### ISSUE TITLE
Treatment of FIX message parsing corner cases   

### ISSUE THREAD

**Issue by KKostya** [AestheticIntegration/fix-engine#4]
The parser produces one of the three results for every message: a ValidMsg message, a Garbled message or a SessionRejectedMessage. There are some situations when it is not very clear whether one should consider a message as Grabled or as SessionRejectedMessage:

The following is pretty clear from FIX specification
   * BeginString<8> not the first tag  -> Garbled
   * MsgType<35> not the third tag -> Garbled
   * BodyLength<9> not the second tag  -> Garbled
   * wrong format for 8=FIX.n.m. -> Garbled
   * 9 does not correspond to byte count of the message body -> Garbled

But there are some corner situations that do not have a specific responce:   
   * duplicate 8 tag -> `?`  Garbled or SessionRejectReason<373> = TagAppearsMoreThanOnce<13>
   * 9 is not properly formatted integer -> `?` Garbled or SessionRejectReason<373> =  IncorrectDataFormat<6>
   * duplicate 9 tag -> `?`  Garbled or   SessionRejectReason<373> = TagAppearsMoreThanOnce<13>
   * 35 value is empty -> `?` Garbled or TagSpecifiedWithoutAValue<4>
   * duplicate 35 tag -> `?`  Garbled or TagAppearsMoreThanOnce<13> or  InvalidMsgType <11>
   * Checksum<10> is not equal to byte count of the message body ->  `?` Garbled or ValueIsIncorrect<5> 

Especially important problem is with sequence number field
   * SeqNumber<34> is not present -> `?` Garbled or RequiredTagMissing<2>
   * SeqNumber<34> is ill formatted -> `?` Garbled or ValueIsIncorrect<5>
   * SeqNumber<34> is empty -> `?` Garbled or TagSpecifiedWithoutAValue<4>

In case If the message is not considered as Garbled when there are problems with SeqNumber<34>, then what must one put in the required field RefSeqNum<45> of the Reject<3> message?

**Comment by ignaden** [comment]
For now, when in question, message is considered Garbled. Comment was added by @KKostya to the readme page for further community discussions.
